import type { Asset } from '../../contract.js';

const base = 'src/projects/vesper-tea/assets/';
const created = { source: 'Original HS108 sample artwork authored for this fictional project', license: 'HS108 sample project asset; may be used within this repository', notes: 'No external client work or third-party imagery.' };
const generated = (prompt: string) => ({ source: 'OpenAI image generation, built-in image_gen tool', license: 'Generated for this fictional sample project', notes: `Original concept scene; no actual venue or product photographed. Prompt: ${prompt}` });
const item = (id: string, file: string, mediaType: Asset['mediaType'], role: string, caption: string, alt: string, cropGuidance: string, mobileCropGuidance: string, audience: Asset['audience'] = ['public', 'client'], extra: Partial<Asset> = {}): Asset => ({ id, path: base + file, mediaType, role, caption, alt, cropGuidance, mobileCropGuidance, audience, rights: created, download: false, ...extra });

export const assets: Asset[] = [
  item('wordmark', 'public/vesper-wordmark.svg', 'image/svg+xml', 'identity', 'Primary wordmark, sample concept.', 'Vesper Tea wordmark with a leaf-shaped V.', 'Contain; leave open space around the lettering.', 'Contain above body copy; never clip the first or last letter.', ['public', 'client'], { aspectRatio: '3:1', focalPoint: { x: 0.5, y: 0.5 } }),
  item('symbol', 'public/vesper-symbol.svg', 'image/svg+xml', 'identity', 'Compact leaf symbol, sample concept.', 'Leaf-shaped V symbol.', 'Contain with even clearance.', 'Keep the whole symbol visible.', ['public', 'client'], { aspectRatio: '1:1', focalPoint: { x: 0.5, y: 0.5 } }),
  item('line-device', 'public/line-device.svg', 'image/svg+xml', 'graphic language', 'The interval line frames and divides.', 'Thin horizontal line bends into a leaf-like pause at its center.', 'Use as a full-width divider, not a photographic crop.', 'Fit to width; preserve its center bend.', ['public', 'client'], { aspectRatio: '3:1' }),
  item('mark-study', 'public/mark-study.svg', 'image/svg+xml', 'identity study', 'The line and leaf geometry behind the mark.', 'Three simple stages show a line, leaf shape and finished V symbol.', 'Contain all three stages in order.', 'Stack stages vertically in the same reading order.', ['public', 'client'], { aspectRatio: '3:2' }),
  item('palette-sheet', 'public/palette-sheet.svg', 'image/svg+xml', 'palette specimen', 'Roles are linked to pinned Chroma references.', 'Five swatches showing paper, leaf, fresh leaf, warmth and ink roles.', 'Contain all swatches and role labels.', 'Stack swatches in reading order if a renderer reflows the page.', ['public', 'client'], { aspectRatio: '3:2' }),
  item('type-specimen', 'public/type-specimen.svg', 'image/svg+xml', 'type specimen', 'The sample display and body pairing.', 'Large Fraunces sample heading above smaller DM Sans explanatory text.', 'Contain typography; do not crop letters.', 'Render a live-text equivalent on narrow screens.', ['public', 'client'], { aspectRatio: '3:2' }),
  item('packaging-system', 'public/packaging-system.svg', 'image/svg+xml', 'application concept', 'Three fictional blend sleeves share one grid.', 'Three flat tea sleeve concepts with distinct blend names in one consistent layout.', 'Contain all three sleeves.', 'Present sleeves one at a time or stack them.', ['public', 'client'], { aspectRatio: '3:2' }),
  item('package-detail', 'public/package-detail.svg', 'image/svg+xml', 'application detail', 'A proposed label with legible practical information.', 'Close view of a fictional tea label with blend name and steeping instructions.', 'Contain the whole label; allow detail inspection.', 'Keep the instruction text available as live page content.', ['public', 'client'], { aspectRatio: '4:3' }),
  item('digital-menu', 'public/digital-menu.svg', 'image/svg+xml', 'digital concept', 'Concept digital menu with a clear reading order.', 'Mobile menu concept showing three fictional tea blends and a simple order action.', 'Contain the screen; do not imply a working product.', 'Fit full width; retain text size and controls.', ['public', 'client'], { aspectRatio: '3:4' }),
  item('canisters', 'public/tea-canisters-concept.png', 'image/png', 'hero application concept', 'Generated concept canisters in a tea setting.', 'Three unbranded paper tea canisters with green bands on a walnut table.', 'Landscape: anchor the three canisters near center; protect the left cup and right plant only when space permits.', 'Portrait: crop around all three canisters; allow table edges to leave frame.', ['public', 'client'], { aspectRatio: '3:2', focalPoint: { x: 0.61, y: 0.54 }, rights: generated('Three matte tea canisters on walnut, soft side light, no text or logos.') }),
  item('room', 'public/tea-room-concept.png', 'image/png', 'environment concept', 'Generated tea counter environment concept.', 'Sunlit timber tea counter with a teapot, cups and jars; no people.', 'Portrait: keep the counter and shelving visible.', 'Use the native portrait image; place captions after the image.', ['public', 'client'], { aspectRatio: '4:5', focalPoint: { x: 0.5, y: 0.62 }, rights: generated('Quiet tea tasting counter, plaster, timber, ceramics and morning light.') }),
  item('still-life', 'public/tea-still-life-concept.png', 'image/png', 'campaign concept', 'Generated tea ritual still life concept.', 'Ceramic cup of amber tea beside loose leaves and a blank folded card.', 'Landscape: retain cup and card as the two anchors.', 'Portrait: center on cup; the card may move outside the crop.', ['public', 'client'], { aspectRatio: '3:2', focalPoint: { x: 0.48, y: 0.5 }, rights: generated('Ceramic teacup, loose leaves and blank folded card in afternoon light.') }),
  item('logo-reveal', 'public/vesper-reveal.json', 'application/json', 'vector motion', 'One short symbol reveal.', 'The V and leaf symbol appears once and holds.', 'Play within its original square composition.', 'Use the static symbol on narrow or low-power contexts.', ['public', 'client'], { aspectRatio: '1:1', motion: { posterAssetId: 'symbol', reducedMotion: 'Show the static symbol immediately with no entrance motion.', playback: 'User-triggered, silent, one play; replay control optional.' } }),
  item('client-wordmark', 'client/vesper-wordmark-primary-v0.1.svg', 'image/svg+xml', 'approved sample download', 'Primary vector wordmark, sample handover.', 'Primary Vesper Tea wordmark vector.', 'Use original vector dimensions.', 'Download file; do not crop.', ['client'], { aspectRatio: '3:1', download: true }),
  item('client-symbol', 'client/vesper-symbol-compact-v0.1.svg', 'image/svg+xml', 'approved sample download', 'Compact vector symbol, sample handover.', 'Compact Vesper Tea leaf symbol vector.', 'Use original vector dimensions.', 'Download file; do not crop.', ['client'], { aspectRatio: '1:1', download: true }),
  item('client-reversed', 'client/vesper-wordmark-reversed-v0.1.svg', 'image/svg+xml', 'approved sample download', 'Reversed vector wordmark for dark fields.', 'Light Vesper Tea wordmark vector on a dark green field.', 'Use only over sufficiently dark approved backgrounds.', 'Download file; do not crop.', ['client'], { aspectRatio: '3:1', download: true }),
  item('logo-construction', 'client/logo-construction.svg', 'image/svg+xml', 'rule diagram', 'A simple clearance and scaling diagram.', 'Primary wordmark with one symbol-height of clearance marked on each side.', 'Contain all measurements and caption.', 'Place diagram before explanatory text.', ['client'], { aspectRatio: '3:2' }),
  item('logo-misuse', 'client/logo-misuse.svg', 'image/svg+xml', 'rule diagram', 'Labeled incorrect examples.', 'Examples show a stretched, rotated and shadowed logo marked as incorrect.', 'Contain labels and examples.', 'Stack each example with its label.', ['client'], { aspectRatio: '3:2' }),
  item('layout-guide', 'client/layout-guide.svg', 'image/svg+xml', 'rule diagram', 'Landscape and portrait composition guide.', 'Diagram compares a wide image with information rail to a portrait header and image sequence.', 'Contain both frames.', 'Show portrait frame first at compact width.', ['client'], { aspectRatio: '3:2' }),
  item('client-tokens', 'client/brand-tokens-v0.1.json', 'application/json', 'sample handover download', 'Semantic palette references and font roles.', 'JSON file containing brand role references, no visual content.', 'Offer as a download link.', 'Offer as a download link.', ['client'], { download: true }),
  item('client-guide', 'client/usage-guide-v0.1.md', 'text/markdown', 'sample handover download', 'Versioned usage notes and vendor checklist.', 'Markdown guide for the fictional identity system.', 'Offer as a download link.', 'Offer as a download link.', ['client'], { download: true })
];
